### ISSUE TITLE
ARC中weak实现 一文中的问题

### ISSUE THREAD

**Issue by aldirc** [NSOiO/nsoio.github.io#1]
你好：
     [《ARC中weak实现》](http://nsoio.github.io/2015/06/28/ARC%E4%B8%ADweak%E5%AE%9E%E7%8E%B0/)中提到了源码经过编译器生成汇编代码，请问是怎么做到的？
      我试过用命令:clang -S xxx.m，编译错误，提示不支持弱引用类型。

**Comment by NSOiO** [comment]
Product - Perform Action - Assemble ...

**Comment by aldirc** [comment]
谢谢
